FROM node:22-alpine AS base
WORKDIR /app
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

FROM base AS deps
COPY . .
RUN pnpm install --frozen-lockfile

FROM deps AS builder
ARG APP_FILTER
ARG NEXT_PUBLIC_DATA_SOURCE=mock
ARG NEXT_PUBLIC_APP_ORIGIN=http://localhost:3001
ENV NEXT_PUBLIC_DATA_SOURCE=$NEXT_PUBLIC_DATA_SOURCE
ENV NEXT_PUBLIC_APP_ORIGIN=$NEXT_PUBLIC_APP_ORIGIN
RUN pnpm --filter "$APP_FILTER" build

FROM base AS runner
ENV NODE_ENV=production
ARG APP_FILTER
ARG NEXT_PUBLIC_DATA_SOURCE=mock
ARG NEXT_PUBLIC_APP_ORIGIN=http://localhost:3001
ENV APP_FILTER=$APP_FILTER
ENV NEXT_PUBLIC_DATA_SOURCE=$NEXT_PUBLIC_DATA_SOURCE
ENV NEXT_PUBLIC_APP_ORIGIN=$NEXT_PUBLIC_APP_ORIGIN
COPY --from=builder /app /app
CMD ["sh", "-c", "pnpm --filter \"$APP_FILTER\" start"]
